# Generated by Django 4.2.1 on 2023-06-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pcm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('mobno', models.IntegerField(null=True)),
                ('comcat', models.CharField(max_length=50)),
                ('comdt', models.DateTimeField()),
                ('comdis', models.CharField(max_length=100)),
            ],
        ),
    ]
