# Generated by Django 4.2.1 on 2023-06-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pcm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcm',
            name='comdt',
            field=models.DateField(),
        ),
    ]
