# Generated by Django 5.0.2 on 2024-03-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_adminl'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcm',
            name='acta',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
