# Generated by Django 5.0.2 on 2024-03-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_pcm_acta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcm',
            name='actiondis',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcm',
            name='actionname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
