# Generated by Django 5.0.2 on 2024-03-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_pcm_actiondis_pcm_actionname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcm',
            name='actiondis',
        ),
        migrations.RemoveField(
            model_name='pcm',
            name='actionname',
        ),
    ]
