# Generated by Django 5.0.2 on 2024-03-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_pcm_actiondis_remove_pcm_actionname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actiontake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobno', models.IntegerField(null=True)),
                ('comcat', models.CharField(max_length=50)),
                ('comdt', models.DateTimeField()),
                ('comdis', models.CharField(max_length=100)),
                ('acta', models.CharField(max_length=50)),
                ('actionname', models.CharField(max_length=50)),
                ('actiondis', models.CharField(max_length=500)),
                ('actiondate', models.DateTimeField()),
            ],
        ),
    ]
